defmodule AcqdatCore.Metrics.Metrics do
  @moduledoc """
  A module for handling all the organisation related metrics.

  The module handles the core logic to aggregate organisation metrics.
  An organisation has the following artifacts which needs to be tracked:
  - `Projects` See `AcqdatCore.Schema.EntityManagement.Project`
  - `Assets` See `AcqdatCore.Schema.EntityManagement.Asset`
  - `Sensors` See `AcqdatCore.Schema.EntityManagement.Sensor`
  - `AssetTypes` See `AcqdatCore.Schema.EntityManagement.AssetType`
  - `SensorTypes` See `AcqdatCore.Schema.EntityManagement.SensorType`
  - `Gateways` See `AcqdatCore.Schema.IotManager.Gateway`
  - `Active Parameters`
  - `Dashboards` See `AcqdatCore.DashboardManagement.Schema.Dashboard`
  - `Data Insights Fact Tabkes` See See `AcqdatCore.DataInsights.Schema.FactTables`
  - `Data Insights Visualisations` See `AcqdatCore.DataInsights.Schema.Visualizations`

  Other than above entities certain more attrbutes are tracked such as:
  - `Active Parameters`: Number of sensor parameters which are receiving data on a
  daily basis
  - `Reports Download`: Number of reports being donwloaded from the dashboard.

  Other than above parameters there should be a provision to monitor the bandwidth
  and data storage being consumed by an organisation.

  The following entities are logged on a daily basis to keep a track of the
  artifacts being generated by the users of an organisation. The artifacts are
  then aggregated monthly to give an insight into resource usage per organisation.

  ## Algorithm
  The current algorithm checks all the above artifacts being created for an
  organisation and then logs them. The logs are then aggregated every month for
  or uptil the given date to give the trends for a specific month.
  """
  @doc """
  Returns the monthly report for an organisation.

  Expects a month in the integer representation or a date as the input.
  """
  @spec monthly_report(integer(), integer() | String.t()) :: map()
  def monthly_report(org_id, month) when is_integer(month) do
  end

  def monthly_report(org, date) do
  end

  @doc """
  Returns the daily report for an organisation.
  """
  def daily_report() do
  end
end
