version: "3.1"

services:
  database:
    image: timescale/timescaledb:latest-pg11
    restart: always
    ports: 
      - 5431:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: acqdat_prod
    volumes: 
      - pgdata:/var/lib/postgresql/data
  
  elastic_search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    restart: always
    container_name: es01
    environment: 
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes: 
      - esdata:/usr/share/elasticsearch/data
    ports: 
      - 9200:9200
  
  mqtt_broker:
    build:
      context: ../../
      dockerfile: ./devops/local/mqtt/Dockerfile
      args:
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
    restart: always
    ports:
      - 1882:1883
    volumes:
      - vernemqdata:/vernemq/data
      - vernemqlogs:/vernemq/logs
      - vernemqetc:/vernemq/etc
    depends_on:
      - database
  
  web:
    build: 
      context: ../../
      dockerfile: ./devops/local/Dockerfile
    restart: always
    container_name: web_app
    ports:
      - 4001:4001
      - 4000:4000
    environment:
      APP_IOT_PORT: ${APP_IOT_PORT}
      APP_API_PORT: ${APP_API_PORT}
      APP_HOSTNAME: ${APP_HOSTNAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      SENDGRID_KEY: ${SENDGRID_KEY}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      GUARDIAN_API_KEY: ${GUARDIAN_API_KEY}
      GUARDIAN_IOT_KEY: ${GUARDIAN_IOT_KEY}
      MQTT_HOST: ${MQTT_HOST}
      MQTT_PORT: ${MQTT_PORT}
    depends_on:
      - database
      - elastic_search
      - mqtt_broker

volumes: 
  esdata:
  pgdata:
  vernemqdata:
  vernemqlogs:
  vernemqetc:
