name: Elixir CI

on:
  push: {branches: master}
  pull_request: {branches: master}
  repository_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    container:
      image: elixir:1.9.1-slim
      env:
        MIX_ENV: test

    services: 
      db:
        image: timescale/timescaledb:latest-pg11
        ports: 
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options:  --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v1
    - name: Add Build essential
      run: apt-get update && apt-get install -y git && apt-get install -y make && apt-get -y install build-essential && apt-get install -y curl
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Check code formatting
      run: mix format --check-formatted
    - name: Run tests (with coverage)
      run:  mix coveralls.json --umbrella
      env:
        DB_HOST: db
    - name: Report coverage to Codecov
      uses: codecov/codecov-action@v1 
      with: 
        file: ./cover/excoveralls.json
